Organise and update GitHub Actions (#99)
* Add GitHub token permissions Monitor action

* Combine python lint and test workflows

* Add custom pytest arguments

* Rename combined python lint+pytest action

* Set black target-version

* Update python lint and format job actions

* Fix isort not given path

* Remove black --verbose setting

* Manually setup python dependencies for CodeQL

* Group all github action together

* Set permissions based on analysis results

Remove GitHubSecurityLab/actions-permissions/monitor

* Set permissions. Remove GitHub Permissions Monitor

* Create workflow to label dependabot pull requests

* Rename workflow and use dependabot/fetch-metadata

* Add check for semver: label on most pull requests

PR labled documentation or maintenance are exempt

* Add label triggers and concurrency group

cancel-in-progress is true

* Use GitHub CLI to add labels instead of an action

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -1,4 +1,4 @@
-name: Python Tests
+name: Python Checks
 on:
   pull_request:
     types:
@@ -11,8 +11,59 @@ on:
       - master
 
 jobs:
+  linting:
+    runs-on: ubuntu-latest
+    permissions: {}
+    steps:
+      # Get repo, python, and poetry
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        id: setup-python
+        with:
+          python-version: "3.11"
+
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          version: 1.6.1
+          virtualenvs-create: true
+          virtualenvs-in-project: true
+          installer-parallel: true
+
+      # Load cached venv if cache exists, else install with poetry
+      - name: Load cached venv
+        id: cached-poetry-dependencies
+        uses: actions/cache@v3
+        with:
+          path: .venv
+          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
+
+      - name: Poetry install dependencies
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
+        run: poetry install --with dev --no-interaction --no-root
+
+      # Run linting, formatting, etc.
+      # if success() || failure() is used to ensure all steps run, even if one fails
+
+      - name: Format with Black
+        uses: psf/black@stable
+        with:
+          options: --check --diff --color --target-version py311
+
+      - name: Format with isort
+        if: success() || failure()
+        run: poetry run isort . --check-only --diff --profile black
+
+      - name: Lint with Ruff
+        if: success() || failure()
+        run: poetry run ruff check src/ tests/
+
   pytest:
     runs-on: ubuntu-latest
+    permissions: {}
     steps:
       # Get repo, python, and poetry
       - name: Checkout Repository
@@ -48,6 +99,11 @@ jobs:
         uses: pavelzw/pytest-action@v2.1.3
         with:
           custom-pytest: poetry run pytest
+          custom-arguments: -r a
+          report-title: Pytest Report
+          click-to-expand: true
+          verbose: true
+          emoji: true
         env:
           IPGET_TEST_HEALTHCHECK_SERVER: ${{secrets.PYTEST_IPGET_HEALTHCHECK_SERVER}}
           IPGET_TEST_HEALTHCHECK_UUID: ${{secrets.PYTEST_IPGET_HEALTHCHECK_UUID}}
